/* ==========================================
 * TABLE: GCG_4844_PRE_Import
 * ========================================== */
CREATE TABLE "GCG_4844_PRE_Import"(
 "KEY_ID" IDENTITY DEFAULT '0',
 "ORDER_Core" CHAR(30),
 "BillingCompany" CHAR(50),
 "bFirstName" CHAR(25),
 "bLastName" CHAR(25),
 "bAddress1" CHAR(50),
 "bAddress2" CHAR(50),
 "bCity" CHAR(50),
 "bState" CHAR(3),
 "bZip" CHAR(13),
 "bCountry" CHAR(12),
 "Email" CHAR(100),
 "Phone" CHAR(13),
 "ShippingCompany" CHAR(50),
 "sFirstName" CHAR(25),
 "sLastName" LONGVARCHAR,
 "sAddress1" CHAR(50),
 "sAddress2" CHAR(50),
 "sCity" CHAR(50),
 "sState" CHAR(3),
 "sZip" CHAR(13),
 "sCountry" CHAR(12),
 "Subtotal" NUMERIC(16,6),
 "HazMatFee" NUMERIC(16,6),
 "SH" NUMERIC(16,6),
 "StateTax" NUMERIC(16,6),
 "Total" NUMERIC(16,6),
 "GrandTotal" NUMERIC(16,6),
 "OrderDate" CHAR(50),
 "CreditCardType" CHAR(30),
 "ShipVia" CHAR(20),
 "OrderComments" LONGVARCHAR,
 "SKU" CHAR(20),
 "QTY" NUMERIC(13,4),
 "ItemName" LONGVARCHAR,
 "Amount" NUMERIC(16,6) NOT NULL ,
 "Customer" CHAR(6),
 "Discount" CHAR(50),
 "Fraud" CHAR(50),
 "CountyTax" NUMERIC(16,6),
 "CarrierCodes" CHAR(6),
 "PercentDiscount" NUMERIC(16,6),
 "TAX_SALES_EX_NO" CHAR(20),
 UNIQUE ("KEY_ID"));


